config/routes.rb
Rails.application.routes.draw do
  get  'welcome/index'
  root 'welcome#index'

  resources :events
  resources :groups
  resources :venues do
    collection do
      get 'find_address_by_latlong' 
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
  belongs_to :venue
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :events
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates :title, presence: true
  validates_attachment :logo,
      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events

  geocoded_by :address

  validates :title, presence: true
  validates :address, presence: true

  # Don't waste API calls if the address hasn't changed
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = []
    if params[:city] && params[:dist]
      venues = Venue.near(params[:city],params[:dist])
      events = venues.map { |v| v.events }
      @events = events.flatten
    else
      @events = Event.all
    end
    respond_to do |format|
      format.html
      format.json { render json: @events}
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @event}
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :group_id, :venue_id, :url)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
    respond_to do |format|
      format.html
      format.json { render json: @groups}
    end
  end

  def show
    @group = Group.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @group}
    end
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:title, :description, :url, :logo)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.all
    respond_to do |format|
      format.html
      format.json { render json: @venues}
    end
  end

  def show
    @venue = Venue.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @venue}
    end
  end

  def new
    @venue = Venue.new
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue
    else
      render 'new'
    end
  end

  def update
    @venue = Venue.find(params[:id])

    if @venue.update(venue_params)
      redirect_to @venue
    else
      render 'edit'
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    redirect_to venues_path
  end

  def find_address_by_latlong
    r = Geocoder.search([params[:lat],params[:long]])
    a = r.detect{|x| x.data['types'] == ['postal_code']}.data['formatted_address']
    render :json => "{ \"address\": \"#{a}\" }"
  end

  private
  def venue_params
    params.require(:venue).permit(:title, :description, :latitude, :longitude, :url, :address, :zoom)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue_id %>
  </p>

  <p>
    <%= f.label :group %><br>
    <%= f.text_field :group_id %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>


  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing Events</h1>

<%= link_to 'New Event', new_event_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th>Venue</th>
    <th>Group</th>
    <th>URL</th>
    <th>Actions</th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= link_to event.venue.title, venue_path(event.venue) %></td>
      <td><%= link_to event.group.title, group_path(event.group) %></td>
      <td><%= event.url %></td>
      <td>
        <%= link_to 'Show', event_path(event), class: "btn btn--color-positive" %>
        <%= link_to 'Edit', edit_event_path(event), class: "btn btn--color-warning" %>
        <%= link_to 'Destroy', event_path(event),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: "btn btn--color-negative" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
    <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
    <%= @event.description %>
</p>

<p>
  <strong>Venue:</strong>
    <%= link_to @event.venue.title, venue_path(@event.venue) %>
</p>

<p>
  <strong>Group:</strong>
    <%= link_to @event.group.title, group_path(@event.group) %>
</p>

<p>
  <strong>URL:</strong>
    <%= @event.url %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %> |
<%= link_to 'Destroy', event_path(@event),
  method: :delete,
  data: { confirm: 'Are you sure?' } %>

app/views/groups/_form.html.erb
<%= form_for @group, html: { multipart: true } do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this group from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <%= f.file_field :logo %>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<%= link_to 'New group', new_group_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th>URL</th>
    <th colspan="3"></th>
  </tr>

  <% @groups.each do |group| %>
    <tr>
      <td><%= group.id %></td>
      <td><%= group.title %></td>
      <td><%= group.description %></td>
      <td><%= group.url %></td>
      <td><%= link_to 'Show', group_path(group) %></td>
      <td><%= link_to 'Edit', edit_group_path(group) %></td>
      <td><%= link_to 'Destroy', group_path(group),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
  <strong>Title:</strong>
    <%= @group.title %>
</p>

<p>
  <strong>Description:</strong>
    <%= @group.description %>
</p>

<p>
  <strong>URL:</strong>
    <%= @group.url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @group.logo.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %> |
<%= link_to 'Destroy', group_path(@group),
  method: :delete,
  data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rascal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap"
                                       async defer></script>

  </head>

  <body>
    <!-- <header> -->
      <div class="row">
          <div class="grid-1" style="border-bottom: 1px solid skyblue">
            <%= image_tag "ABCLogo.svg" %>
          </div>
          <div class="grid bottom" style="border-bottom: 1px solid skyblue">
              <ol class="menu">
                <li class="main-nav">
                  <ol>
                    <li><a href="/">Home</a></li>
                    <li><%= link_to 'Events', controller: 'events' %></li>
                    <li><%= link_to 'Groups', controller: 'groups' %></li>
                    <li><%= link_to 'Venues', controller: 'venues' %></li>
                  </ol>
                </li>
              </ol>
          </div>
      </div>
    <!-- </header> -->
    <div class="row">  
      <div class="grid">
        <br />  
        <%= yield %>
      </div>
    </div>    
  </body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rascal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap"
                                       async defer></script>

  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/venues/_form.html.erb
<%= form_for @venue, html: {class: 'labels-default'} do |f| %>

	<div class='row'>
		<div class='grid-12'>
      <% if @venue.errors.any? %>
        <%= field_set_tag nil, class: 'invalid' do %>
        <div id="error_explanation" class="message message--color-negative">
          <h2>
            <%= pluralize(@venue.errors.count, "error") %> prohibited
            this venue from being saved:
          </h2>
          <ul>
            <% @venue.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>

    <%= field_set_tag do %>
      <%= label_tag 'Venue Name *' %>
      <%= f.text_field :title %>
      <%= label_tag 'Venue URL' %>
      <%= f.text_field :url %>
    <% end %>

    <%= field_set_tag do %>
      <%= label_tag 'Description' %>
      <%= f.text_area :description %>
    <% end %>

    <%= field_set_tag do %>
      <%= label_tag 'Address' %>
      <div class="has-inline-elements">
        <%= f.text_area :address %>
        <span class="inline-btn-group">
          <a href="#" id="update-map" class="btn btn--color-positive" type="button">Update map!</a>
        </span>
      </div>
    <% end %>

    <div class="row">
      <div class="grid-8">
        <div id="map"></div>
      </div>
      <div class="grid-4">
        <%= field_set_tag do %>
          <%= label_tag 'Lat' %>
          <%= f.text_field :latitude %>
          <%= label_tag 'Long' %>
          <%= f.text_field :longitude %>
          <%= label_tag 'Zoom' %>
          <%= f.text_field :zoom %>
          <a href="#" id="find-on-map" class="btn btn--color-positive" type="button">Find on map!</a>
        <% end %>
      </div>
    </div>

    <%= f.submit %>

  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>

<%= link_to 'New venue', new_venue_path %>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>URL</th>
    <th colspan="3"></th>
  </tr>

  <% @venues.each do |venue| %>
    <tr>
      <td><%= venue.id %></td>
      <td><%= venue.title %></td>
      <td><%= venue.description %></td>
      <td><%= venue.address %></td>
      <td><%= venue.latitude %></td>
      <td><%= venue.longitude %></td>
      <td><%= venue.url %></td>
      <td><%= link_to 'Show', venue_path(venue) %></td>
      <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
      <td><%= link_to 'Destroy', venue_path(venue),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p>
  <strong>Title:</strong>
    <%= @venue.title %>
</p>

<p>
  <strong>Description:</strong>
    <%= @venue.description %>
</p>

<p>
  <strong>Address:</strong>
    <%= @venue.address %>
</p>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@venue.latitude},#{@venue.longitude}&markers=#{@venue.latitude},#{@venue.longitude}&zoom=#{@venue.zoom || "15"}&size=640x400&key=#{ENV["GOOGLE_API_KEY"]}",
              class: 'img-fluid img-rounded', alt: "#{@venue.title} on the map"%>

<p>
  <strong>URL:</strong>
    <%= @venue.url %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %> |
<%= link_to 'Destroy', venue_path(@venue),
  method: :delete,
  data: { confirm: 'Are you sure?' } %>

app/views/welcome/index.html.erb
<h1>Welcome to Rascal!</h1>

<p>Rascal is an open source shared calendar system, for all users to share their
knowledge of events in their area. Click the links above to get started!</p>

<p>Show me:</p>
<%= form_tag send("events_path"), :method => "get", :class=>"form-search" do %>
        <div class="input">
        <%= text_field_tag(:city, params[:city].try(:squeeze," "), :placeholder => "City" + ' ...', :class => "search-query") %>
        <%= text_field_tag(:dist, params[:dist].try(:squeeze," "), :placeholder => "Distance" + ' ...', :class => "search-query") %>
        <button class="btn btn-inverse search-query" type="submit">Search</button>
        </div>
      <% end %>